[build]
  base    = "packages/web"
  command = "yarn build"
  publish = "packages/web/build"


# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/graphql/*"
  to = "https://api.satisfactory-map.lancelot.dev/:splat"
  status = 200
